# Generated by Django 5.1.1 on 2024-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="city",
            field=models.TextField(max_length=70, verbose_name="город"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="country",
            field=models.TextField(max_length=70, verbose_name="страна"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="street",
            field=models.TextField(max_length=150, verbose_name="улица"),
        ),
    ]
