# Generated by Django 5.1.1 on 2024-10-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_alter_supplier_city_alter_supplier_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="debt",
            field=models.FloatField(
                default=0.0, verbose_name="задолженность перед поставщиком"
            ),
        ),
    ]
