# Generated by Django 5.1.1 on 2024-10-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0003_alter_supplier_debt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=20,
                verbose_name="задолженность перед поставщиком",
            ),
        ),
    ]
